Feature/landingpage jnguyen
TCU-ClassifAI/classifAI pull request #46
Opened 2023-12-24 18:16 UTC by J4ninja

## Type of Change

(Bug fix, new feature, documentation, configuration update, etc.)

## Context

[Insert the issue number or link to the related issue, if applicable]

## Changes Made

- [Insert a bullet point list of the changes made in this pull request]

## Screenshots

[Insert any relevant screenshots, if applicable]

## Checklist

- [ ] I have tested these changes locally
- [ ] I have updated the documentation, if applicable
- [ ] I have added unit tests, if applicable

2023-12-26 05:59 UTC, jhmejia requested changes

2023-12-26 06:01 UTC, J4ninja commented on frontend/src/Footer/Footer.jsx
> +    { name: 'LinkedIn', url: 'https://linkedin.com', icon: faLinkedin },
Any idea to replace it? It looks awkward with two icons

2023-12-27 06:47 UTC, jhmejia commented on frontend/src/Footer/Footer.jsx
> +    { name: 'LinkedIn', url: 'https://linkedin.com', icon: faLinkedin },
perhaps documentation link. Ideally when done it should be good documentation
```suggestion
    { name: 'Documentation', url: 'https://tcu-classifai.github.io/classifAI/', icon: faFolderOpen },
```

2023-12-27 06:47 UTC, jhmejia commented on frontend/src/Footer/Footer.jsx
> +          <a href="#contact">LinkedIn</a>
```suggestion
          <a href="https://tcu-classifai.github.io/classifAI/">Documentation</a>
```

2023-12-30 04:23 UTC, jhmejia approved these changes

2023-12-30 04:30 UTC, merged